export const galleryStudents = [
    {
        photo:
            './images/students/member1.jpg',
        name:
            '',
        profession:
            'Розробник',
        email:
            '',
        GitHub:
            '',
    },
    {
        photo:
            './images/students/member2.jpg',
       name:
            '',
       profession:
            'Розробник',
        email:
            '',
        GitHub:
            '',
    },
    {
        photo:
            './images/students/member3.jpg',
        name:
            '',
        profession:
            'Розробник',
        email:
            '',
        GitHub:
            '',
    },
    {
        photo:
            './images/students/member4.jpg',
        name:
            '',
        profession:
            'Розробник',
        email:
            '',
        GitHub:
            '',
    },
    {
        photo:
            './images/students/member5.jpg',
        name:
            '',
        profession:
            'Розробник',
        email:
            '',
        GitHub:
            '',
    },
    {
        photo:
            './images/students/member6.jpg',
        name:
            '',
        profession:
            'Розробник',
        email:
            '',
        GitHub:
            '',
    },
    {
        photo:
            './images/students/member7.jpg',
        name:
            '',
        profession:
            'Розробник',
        email:
            '',
        GitHub:
            '',
    },
    {
        photo:
            './images/students/member8.jpg',
        name:
            '',
        profession:
            'Розробник',
        email:
            '',
        GitHub:
            '',
    },
    {
        photo:
            './images/students/Карпушина Ирина.jpg',
        name:
            'Карпушина Ірина',
        profession:
            'Розробник',
        email:
            'irnikshu@ukr.net',
        GitHub:
            'https://github.com/irnikshu',
    },
    {
        photo:
            './images/students/member9.jpg',
        name:
            '',
        profession:
            'Розробник',
        email:
            '',
        GitHub:
            '',
    },
    {
        photo:
            './images/students/member10.jpg',
        name:
            '',
        profession:
            'Розробник',
        email:
            '',
        GitHub:
            '',
    },
];